from selenium.webdriver import Chrome
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from bs4 import BeautifulSoup
from email.message import EmailMessage
import ssl
import smtplib
import time
from credentials import gmailUser, gmailPassword, gmailReceiver

urlWords = "https://www.palabrasque.com/palabra-aleatoria.php?Submit=Nueva+palabra"


def sendEmail(word, definitionWord, country, spanCurrentTime):
    # Create message
    subject = "Country and words generator"
    body = f"""
Word generated: {word}.
Definition according to RAE: {definitionWord}
Country generated: {country}.
Current time: {spanCurrentTime}.
"""

    # Initiliazate object and properties
    email = EmailMessage()
    email["From"] = gmailUser
    email["To"] = gmailReceiver
    email["Subject"] = subject
    email.set_content(body)

    context = ssl.create_default_context()

    # Acces gmail server
    with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=context) as smtp:
        smtp.login(gmailUser, gmailPassword)
        smtp.sendmail(gmailUser, gmailReceiver, email.as_string())
        print("Email sent succesfuly!")

def main():
    while True:
        # Initializate driver
        service = Service(ChromeDriverManager().install())
        option = webdriver.ChromeOptions()
        option.add_argument("--log-level=1")
        #option.add_argument("--window-size=1920,1080")
        option.add_argument("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36")
        option.add_argument("--headless") # Doesn't show the window

        driver = Chrome(service = service, options = option)
        driver.get(urlWords)

        soup = BeautifulSoup(driver.page_source, 'html.parser')
        word = soup.find('b').get_text()

        if word: print(f"Word generated succesfuly!")

        # Search the word generated in RAE
        urlRAE = f"https://dle.rae.es/{word}"
        driver.get(urlRAE)
        
        # If the word has definition in RAE
        try:
            # We look for the meaning of the word in the HTML
            soup2 = BeautifulSoup(driver.page_source, 'html.parser')
            olClass = soup2.find('ol', class_="c-definitions")
            liClass = olClass.find('li', class_="j")
            divClass = liClass.find('div', class_="c-definitions__item")
            definitionWord = divClass.find('div').get_text()

            if definitionWord: print(f"Definition generated succesfuly!")

            # Country generator page
            urlCountry = "https://ohmyluck.com/es/random-country/"

            # Go to random country generator and generate a country
            driver.get(urlCountry)
            buttonGenerateCountry = driver.find_element(By.XPATH, "/html/body/main/div[2]/div[2]/button")
            buttonGenerateCountry.click()

            # Wait a little bit until the HTML loads 
            time.sleep(1)

            # Get the country generated by ID 
            country = driver.find_element(By.ID, "name").text
            if country: print(f"Country generated succesfuly!")

            # Timezone generator by country page
            urlTimeZone = f"https://24timezones.com/{country}/hora"

            # Go to page and get hour from HTML
            driver.get(urlTimeZone)

            spanCurrentTime = driver.find_element(By.ID, "currentTime").text
            if spanCurrentTime: print(f"Current time generated succesfuly!")

            sendEmail(word, definitionWord, country, spanCurrentTime)

        except:
            print(f"There was an error!")
            # Dispose browser
            driver.quit()
            # Repeat the function
            continue

        # Dispose browser
        driver.quit()

        # Wait 15 minutes until next message
        time.sleep(900)

if __name__ == "__main__":
    main()
